apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          {{- if .Values.redis.image.digest }}
          image: "{{ .Values.redis.image.repository }}@{{ .Values.redis.image.digest }}"
          {{- end }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}          
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.redis.persistentVolumeClaim }}
