apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: "{{ .Values.meilisearch.image.repository }}:{{ .Values.meilisearch.image.tag }}"
          {{- if .Values.meilisearch.image.digest }}
          image: "{{ .Values.meilisearch.image.repository }}@{{ .Values.meilisearch.image.digest }}"
          {{- end }}
          imagePullPolicy: {{ .Values.meilisearch.image.pullPolicy }}          
          ports:
            - containerPort: {{ .Values.meilisearch.service.port }}
          env:
            - name: MEILI_HOST
              value: "http://meilisearch:7700"
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: meilisearch-pvc
