apiVersion: v1
kind: Service
metadata:
  name: vectordb
  labels:
    app: vectordb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vectordb.service.port }}
      targetPort: {{ .Values.vectordb.service.port }}
      protocol: TCP
      name: vectordb
  selector:
    app: vectordb
